package pcp.interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author jonathan
 */
public class TelaIncial extends javax.swing.JFrame {

    /**
     * Creates new form TelaIncial
     */
    public TelaIncial() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Cadastro Equipamentos Pixar Harcker Club");
        
        pnPessoaFisica.setVisible(false);
        pnPessoaJuridica.setVisible(false);
        

// desabilitar opçoes do painel equipamento
        rbEquipamentoFisica.setEnabled(false);
        rbEquipamentoJuridica.setEnabled(false);
        tfEquipamentoNome.setEnabled(false);
        taEquipamentoDescricao.setEnabled(false);
        btEquipamentoCadastrar.setEnabled(false);
        
  // desabilitar Painel de Pessoa Fisica
       cbxPessoaFisicaNome.setEnabled(false);
       tfFisicaPessoaCPF.setEnabled(false);
       tfFisicaPessoaNome.setEnabled(false);
       tfFisicaPessoaTelefone.setEnabled(false);
       btFisicaPessoaCadastrarPessoa.setEnabled(false);
   

 // desabilitar Painel de Pessoa Juridica 
     cbxPessoaJuridicaNome.setEnabled(false);
     tfPessoaJuridicaCNPJ.setEnabled(false);
     tfPessoaJuridicaNomeFantasia.setEnabled(false);
     tfPessoaJuridicaRazaoSocial.setEnabled(false);
     tfPessoaJuridicaTelefone.setEnabled(false);
     btPessoaJuridicaCadastrarEmpresa.setEnabled(false);
      
       
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgDoacao = new javax.swing.ButtonGroup();
        btgPessoa = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        btgPessoaCadastro = new javax.swing.ButtonGroup();
        btgPessoaJuridicaCadastro = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnEquipamento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbEquipamentoFisica = new javax.swing.JRadioButton();
        rbEquipamentoJuridica = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbEquipamentoSim = new javax.swing.JRadioButton();
        rbEqupamentoNao = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfEquipamentoNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taEquipamentoDescricao = new javax.swing.JTextArea();
        btEquipamentoSair = new javax.swing.JButton();
        btEquipamentoCadastrar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnPessoaFisica = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbFisicaPessoaNaoCadastrada = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cbxPessoaFisicaNome = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfFisicaPessoaNome = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfFisicaPessoaTelefone = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        tfFisicaPessoaCPF = new javax.swing.JFormattedTextField();
        btFisicaPessoaCadastrarPessoa = new javax.swing.JButton();
        cbFisicaPessoaCadastrada = new javax.swing.JCheckBox();
        pnPessoaJuridica = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cbPessoaJuridicaEmpresaNaoCadastrada = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        cbxPessoaJuridicaNome = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfPessoaJuridicaRazaoSocial = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfPessoaJuridicaNomeFantasia = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfPessoaJuridicaCNPJ = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        tfPessoaJuridicaTelefone = new javax.swing.JFormattedTextField();
        btPessoaJuridicaCadastrarEmpresa = new javax.swing.JButton();
        cbPessoaJuridicaEmpresaCadastrada = new javax.swing.JCheckBox();

        jCheckBox1.setText("jCheckBox1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnEquipamento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Cadastrar Equipamento");

        btgPessoa.add(rbEquipamentoFisica);
        rbEquipamentoFisica.setText("fisica");
        rbEquipamentoFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEquipamentoFisicaActionPerformed(evt);
            }
        });

        btgPessoa.add(rbEquipamentoJuridica);
        rbEquipamentoJuridica.setText("juridica");
        rbEquipamentoJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEquipamentoJuridicaActionPerformed(evt);
            }
        });

        jLabel2.setText("Doação");

        btgDoacao.add(rbEquipamentoSim);
        rbEquipamentoSim.setText("Sim");
        rbEquipamentoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEquipamentoSimActionPerformed(evt);
            }
        });

        btgDoacao.add(rbEqupamentoNao);
        rbEqupamentoNao.setText("Não");
        rbEqupamentoNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEqupamentoNaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de Pessoa");

        jLabel5.setText("Nome Equipamento");

        jLabel6.setText("Descrição");

        taEquipamentoDescricao.setColumns(20);
        taEquipamentoDescricao.setRows(5);
        jScrollPane1.setViewportView(taEquipamentoDescricao);

        btEquipamentoSair.setText("Sair");
        btEquipamentoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEquipamentoSairActionPerformed(evt);
            }
        });

        btEquipamentoCadastrar.setText("Cadastrar");

        javax.swing.GroupLayout pnEquipamentoLayout = new javax.swing.GroupLayout(pnEquipamento);
        pnEquipamento.setLayout(pnEquipamentoLayout);
        pnEquipamentoLayout.setHorizontalGroup(
            pnEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEquipamentoLayout.createSequentialGroup()
                .addGroup(pnEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEquipamentoLayout.createSequentialGroup()
                        .addGroup(pnEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnEquipamentoLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(pnEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnEquipamentoLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(pnEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnEquipamentoLayout.createSequentialGroup()
                                        .addComponent(rbEquipamentoFisica)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbEquipamentoJuridica))
                                    .addGroup(pnEquipamentoLayout.createSequentialGroup()
                                        .addComponent(rbEquipamentoSim)
                                        .addGap(30, 30, 30)
                                        .addComponent(rbEqupamentoNao))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(pnEquipamentoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tfEquipamentoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnEquipamentoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnEquipamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pnEquipamentoLayout.createSequentialGroup()
                                .addComponent(btEquipamentoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btEquipamentoCadastrar)))))
                .addContainerGap())
        );
        pnEquipamentoLayout.setVerticalGroup(
            pnEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEquipamentoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEquipamentoSim)
                    .addComponent(rbEqupamentoNao))
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEquipamentoFisica)
                    .addComponent(rbEquipamentoJuridica))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfEquipamentoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEquipamentoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEquipamentoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(pnEquipamento);

        pnPessoaFisica.setBackground(new java.awt.Color(255, 255, 255));
        pnPessoaFisica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setText("Cadastro Pessoa Fisica");

        btgPessoaCadastro.add(cbFisicaPessoaNaoCadastrada);
        cbFisicaPessoaNaoCadastrada.setText("Pessoa Nao cadastrada:");
        cbFisicaPessoaNaoCadastrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFisicaPessoaNaoCadastradaActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome:");

        cbxPessoaFisicaNome.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Cadastrar Nova Pessoa");

        jLabel10.setText("Nome:");

        jLabel11.setText("Telefone:");

        try {
            tfFisicaPessoaTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("CPF:");

        try {
            tfFisicaPessoaCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btFisicaPessoaCadastrarPessoa.setText("Cadastrar Pessoa");

        btgPessoaCadastro.add(cbFisicaPessoaCadastrada);
        cbFisicaPessoaCadastrada.setText("Pessoa Cadastrada");
        cbFisicaPessoaCadastrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFisicaPessoaCadastradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPessoaFisicaLayout = new javax.swing.GroupLayout(pnPessoaFisica);
        pnPessoaFisica.setLayout(pnPessoaFisicaLayout);
        pnPessoaFisicaLayout.setHorizontalGroup(
            pnPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPessoaFisicaLayout.createSequentialGroup()
                .addGroup(pnPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPessoaFisicaLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel9))
                    .addGroup(pnPessoaFisicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFisicaPessoaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPessoaFisicaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnPessoaFisicaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cbxPessoaFisicaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPessoaFisicaLayout.createSequentialGroup()
                                .addComponent(cbFisicaPessoaNaoCadastrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbFisicaPessoaCadastrada))
                            .addGroup(pnPessoaFisicaLayout.createSequentialGroup()
                                .addGroup(pnPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(pnPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfFisicaPessoaNome)
                                    .addGroup(pnPessoaFisicaLayout.createSequentialGroup()
                                        .addComponent(tfFisicaPessoaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPessoaFisicaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPessoaFisicaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPessoaFisicaLayout.createSequentialGroup()
                        .addComponent(btFisicaPessoaCadastrarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        pnPessoaFisicaLayout.setVerticalGroup(
            pnPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPessoaFisicaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFisicaPessoaNaoCadastrada)
                    .addComponent(cbFisicaPessoaCadastrada))
                .addGap(18, 18, 18)
                .addGroup(pnPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxPessoaFisicaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(pnPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfFisicaPessoaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(tfFisicaPessoaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfFisicaPessoaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btFisicaPessoaCadastrarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnPessoaJuridica.setBackground(new java.awt.Color(255, 255, 204));
        pnPessoaJuridica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel13.setText("Cadastro Pessoa Juridica");

        btgPessoaJuridicaCadastro.add(cbPessoaJuridicaEmpresaNaoCadastrada);
        cbPessoaJuridicaEmpresaNaoCadastrada.setText("Empresa Não Cadastrada");
        cbPessoaJuridicaEmpresaNaoCadastrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPessoaJuridicaEmpresaNaoCadastradaActionPerformed(evt);
            }
        });

        jLabel14.setText("Nome:");

        cbxPessoaJuridicaNome.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Cadastrar Nova Empresa");

        jLabel16.setText("Razão Social:");

        jLabel17.setText("Nome Fantasia");

        jLabel18.setText("CNPJ:");

        try {
            tfPessoaJuridicaCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel19.setText("Telefone:");

        try {
            tfPessoaJuridicaTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btPessoaJuridicaCadastrarEmpresa.setText("Cadastrar Empresa");

        btgPessoaJuridicaCadastro.add(cbPessoaJuridicaEmpresaCadastrada);
        cbPessoaJuridicaEmpresaCadastrada.setText("Empresa Cadastrada");
        cbPessoaJuridicaEmpresaCadastrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPessoaJuridicaEmpresaCadastradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPessoaJuridicaLayout = new javax.swing.GroupLayout(pnPessoaJuridica);
        pnPessoaJuridica.setLayout(pnPessoaJuridicaLayout);
        pnPessoaJuridicaLayout.setHorizontalGroup(
            pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPessoaJuridicaLayout.createSequentialGroup()
                .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPessoaJuridicaLayout.createSequentialGroup()
                        .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPessoaJuridicaLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnPessoaJuridicaLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(27, 27, 27)
                                        .addComponent(cbxPessoaJuridicaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnPessoaJuridicaLayout.createSequentialGroup()
                                        .addComponent(cbPessoaJuridicaEmpresaNaoCadastrada)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbPessoaJuridicaEmpresaCadastrada))))
                            .addGroup(pnPessoaJuridicaLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel15))
                            .addGroup(pnPessoaJuridicaLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnPessoaJuridicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPessoaJuridicaLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfPessoaJuridicaRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPessoaJuridicaLayout.createSequentialGroup()
                                .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(22, 22, 22)
                                .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPessoaJuridicaNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfPessoaJuridicaCNPJ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(tfPessoaJuridicaTelefone, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPessoaJuridicaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btPessoaJuridicaCadastrarEmpresa)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnPessoaJuridicaLayout.setVerticalGroup(
            pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPessoaJuridicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPessoaJuridicaEmpresaNaoCadastrada)
                    .addComponent(cbPessoaJuridicaEmpresaCadastrada))
                .addGap(18, 18, 18)
                .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbxPessoaJuridicaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(29, 29, 29)
                .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfPessoaJuridicaRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPessoaJuridicaNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfPessoaJuridicaCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfPessoaJuridicaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btPessoaJuridicaCadastrarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnPessoaFisica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnPessoaJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnPessoaFisica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnPessoaJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1.setLayer(pnPessoaFisica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pnPessoaJuridica, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSplitPane1.setRightComponent(jLayeredPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbEquipamentoFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEquipamentoFisicaActionPerformed
        // TODO add your handling code here:
        pnPessoaJuridica.setVisible(false);
        pnPessoaFisica.setVisible(true);
    }//GEN-LAST:event_rbEquipamentoFisicaActionPerformed

    private void rbEquipamentoJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEquipamentoJuridicaActionPerformed
        // TODO add your handling code here:
        pnPessoaFisica.setVisible(false);
        pnPessoaJuridica.setVisible(true);
    }//GEN-LAST:event_rbEquipamentoJuridicaActionPerformed

    private void rbEqupamentoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEqupamentoNaoActionPerformed
        // TODO add your handling code here:
        tfEquipamentoNome.setEnabled(true);
        taEquipamentoDescricao.setEnabled(true);
        btEquipamentoCadastrar.setEnabled(true);
        rbEquipamentoFisica.setEnabled(false);
        rbEquipamentoJuridica.setEnabled(false);
          pnPessoaJuridica.setVisible(false);
          pnPessoaFisica.setVisible(false);

    }//GEN-LAST:event_rbEqupamentoNaoActionPerformed

    private void rbEquipamentoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEquipamentoSimActionPerformed
        // TODO add your handling code here:
        btgPessoa.clearSelection();
        tfEquipamentoNome.setEnabled(true);
        taEquipamentoDescricao.setEnabled(true);
        rbEquipamentoFisica.setEnabled(true);
        rbEquipamentoJuridica.setEnabled(true);
        btEquipamentoCadastrar.setEnabled(false);
    }//GEN-LAST:event_rbEquipamentoSimActionPerformed

    private void btEquipamentoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEquipamentoSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btEquipamentoSairActionPerformed

    private void cbFisicaPessoaNaoCadastradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFisicaPessoaNaoCadastradaActionPerformed
        // TODO add your handling code here:
        cbxPessoaFisicaNome.setEnabled(false);
        tfFisicaPessoaCPF.setEnabled(true);
        tfFisicaPessoaNome.setEnabled(true);
        tfFisicaPessoaTelefone.setEnabled(true);
        btFisicaPessoaCadastrarPessoa.setEnabled(true);
        btEquipamentoCadastrar.setEnabled(false);
        
    }//GEN-LAST:event_cbFisicaPessoaNaoCadastradaActionPerformed

    private void cbFisicaPessoaCadastradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFisicaPessoaCadastradaActionPerformed
        // TODO add your handling code here:
        cbxPessoaFisicaNome.setEnabled(true);
        tfFisicaPessoaCPF.setEnabled(false);
        tfFisicaPessoaNome.setEnabled(false);
        tfFisicaPessoaTelefone.setEnabled(false);
        btFisicaPessoaCadastrarPessoa.setEnabled(false);
        btEquipamentoCadastrar.setEnabled(true);
    }//GEN-LAST:event_cbFisicaPessoaCadastradaActionPerformed

    private void cbPessoaJuridicaEmpresaNaoCadastradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPessoaJuridicaEmpresaNaoCadastradaActionPerformed
        // TODO add your handling code here:
        cbxPessoaJuridicaNome.setEnabled(false);
        tfPessoaJuridicaCNPJ.setEnabled(true);
        tfPessoaJuridicaNomeFantasia.setEnabled(true);
        tfPessoaJuridicaRazaoSocial.setEnabled(true);
        tfPessoaJuridicaTelefone.setEnabled(true);
        btPessoaJuridicaCadastrarEmpresa.setEnabled(true);
        btEquipamentoCadastrar.setEnabled(false);
    }//GEN-LAST:event_cbPessoaJuridicaEmpresaNaoCadastradaActionPerformed

    private void cbPessoaJuridicaEmpresaCadastradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPessoaJuridicaEmpresaCadastradaActionPerformed
        // TODO add your handling code here:
         cbxPessoaJuridicaNome.setEnabled(true);
        tfPessoaJuridicaCNPJ.setEnabled(false);
        tfPessoaJuridicaNomeFantasia.setEnabled(false);
        tfPessoaJuridicaRazaoSocial.setEnabled(false);
        tfPessoaJuridicaTelefone.setEnabled(false);
        btPessoaJuridicaCadastrarEmpresa.setEnabled(false);
        btEquipamentoCadastrar.setEnabled(true);
    }//GEN-LAST:event_cbPessoaJuridicaEmpresaCadastradaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEquipamentoCadastrar;
    private javax.swing.JButton btEquipamentoSair;
    private javax.swing.JButton btFisicaPessoaCadastrarPessoa;
    private javax.swing.JButton btPessoaJuridicaCadastrarEmpresa;
    private javax.swing.ButtonGroup btgDoacao;
    private javax.swing.ButtonGroup btgPessoa;
    private javax.swing.ButtonGroup btgPessoaCadastro;
    private javax.swing.ButtonGroup btgPessoaJuridicaCadastro;
    private javax.swing.JCheckBox cbFisicaPessoaCadastrada;
    private javax.swing.JCheckBox cbFisicaPessoaNaoCadastrada;
    private javax.swing.JCheckBox cbPessoaJuridicaEmpresaCadastrada;
    private javax.swing.JCheckBox cbPessoaJuridicaEmpresaNaoCadastrada;
    private javax.swing.JComboBox cbxPessoaFisicaNome;
    private javax.swing.JComboBox cbxPessoaJuridicaNome;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnEquipamento;
    private javax.swing.JPanel pnPessoaFisica;
    private javax.swing.JPanel pnPessoaJuridica;
    private javax.swing.JRadioButton rbEquipamentoFisica;
    private javax.swing.JRadioButton rbEquipamentoJuridica;
    private javax.swing.JRadioButton rbEquipamentoSim;
    private javax.swing.JRadioButton rbEqupamentoNao;
    private javax.swing.JTextArea taEquipamentoDescricao;
    private javax.swing.JTextField tfEquipamentoNome;
    private javax.swing.JFormattedTextField tfFisicaPessoaCPF;
    private javax.swing.JTextField tfFisicaPessoaNome;
    private javax.swing.JFormattedTextField tfFisicaPessoaTelefone;
    private javax.swing.JFormattedTextField tfPessoaJuridicaCNPJ;
    private javax.swing.JTextField tfPessoaJuridicaNomeFantasia;
    private javax.swing.JTextField tfPessoaJuridicaRazaoSocial;
    private javax.swing.JFormattedTextField tfPessoaJuridicaTelefone;
    // End of variables declaration//GEN-END:variables

}
